"""add_hydration_logs

Revision ID: bf1fe926a7be
Revises: 9a8b7c6d5e4f
Create Date: 2025-12-16 02:07:31.926043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1fe926a7be'
down_revision: Union[str, None] = '9a8b7c6d5e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Float(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hydration_logs_logged_at'), 'hydration_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_hydration_logs_user_id'), 'hydration_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_food_products_name'), table_name='food_products')
    op.create_index(op.f('ix_food_products_name'), 'food_products', ['name'], unique=False)
    op.create_index(op.f('ix_food_products_user_id'), 'food_products', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_products_user_id'), table_name='food_products')
    op.drop_index(op.f('ix_food_products_name'), table_name='food_products')
    op.create_index(op.f('ix_food_products_name'), 'food_products', ['name'], unique=True)
    op.drop_index(op.f('ix_hydration_logs_user_id'), table_name='hydration_logs')
    op.drop_index(op.f('ix_hydration_logs_logged_at'), table_name='hydration_logs')
    op.drop_table('hydration_logs')
    # ### end Alembic commands ###

