"""add image_url to programs

Revision ID: 97cbdd27a8a7
Revises: 74615ff67d3b
Create Date: 2025-12-03 01:22:12.900912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cbdd27a8a7'
down_revision: Union[str, None] = '74615ff67d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'image_url')
    # ### end Alembic commands ###

