"""update_exercise_fields_to_arrays

Revision ID: 53df928e32aa
Revises: 97cbdd27a8a7
Create Date: 2025-12-06 01:07:03.354106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53df928e32aa'
down_revision: Union[str, None] = '97cbdd27a8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('exercises', sa.Column('muscle_groups', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('exercises', sa.Column('video_urls', postgresql.ARRAY(sa.String()), nullable=True))
    
    # 2. Data migration: Copy existing data to new array columns
    op.execute("UPDATE exercises SET muscle_groups = ARRAY[muscle_group]")
    op.execute("UPDATE exercises SET video_urls = ARRAY[video_url] WHERE video_url IS NOT NULL")
    
    # 3. Set muscle_groups to not null (now that it has data)
    op.alter_column('exercises', 'muscle_groups', nullable=False)

    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.create_index(op.f('ix_exercises_muscle_groups'), 'exercises', ['muscle_groups'], unique=False)
    op.drop_column('exercises', 'muscle_group')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('exercises', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('muscle_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # 2. Data migration (Downgrade): Take first element of arrays
    op.execute("UPDATE exercises SET muscle_group = muscle_groups[1]")
    op.execute("UPDATE exercises SET video_url = video_urls[1] WHERE video_urls IS NOT NULL AND array_length(video_urls, 1) > 0")

    # 3. Set muscle_group to not null
    op.alter_column('exercises', 'muscle_group', nullable=False)

    op.drop_index(op.f('ix_exercises_muscle_groups'), table_name='exercises')
    op.create_index(op.f('ix_exercises_muscle_group'), 'exercises', ['muscle_group'], unique=False)
    op.drop_column('exercises', 'video_urls')
    op.drop_column('exercises', 'muscle_groups')
    # ### end Alembic commands ###

