"""add_target_macros_to_user_profile

Revision ID: 6108a3aa8ab7
Revises: bf1fe926a7be
Create Date: 2025-12-16 02:43:55.654984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6108a3aa8ab7'
down_revision: Union[str, None] = 'bf1fe926a7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('target_proteins', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_fats', sa.Float(), nullable=True))
    op.add_column('user_profiles', sa.Column('target_carbs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'target_carbs')
    op.drop_column('user_profiles', 'target_fats')
    op.drop_column('user_profiles', 'target_proteins')
    # ### end Alembic commands ###

