"""add target_muscle_groups to programs

Revision ID: 74615ff67d3b
Revises: c1a2b3d4e5f6
Create Date: 2025-12-02 23:41:45.035841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74615ff67d3b'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('target_muscle_groups', sa.String(), nullable=True))
    op.create_index(op.f('ix_workout_logs_program_id'), 'workout_logs', ['program_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_program_id'), table_name='workout_logs')
    op.drop_column('programs', 'target_muscle_groups')
    # ### end Alembic commands ###

