"""add_target_calories

Revision ID: ada7dc7ac356
Revises: 8d83968937e9
Create Date: 2025-11-30 21:59:12.024867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada7dc7ac356'
down_revision: Union[str, None] = '8d83968937e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('target_calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'target_calories')
    # ### end Alembic commands ###

